# Generated by Django 5.2 on 2025-06-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
