# Generated by Django 5.2 on 2025-06-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.atendimento')),
            ],
        ),
    ]
