# Generated by Django 5.2 on 2025-06-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('prescricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prescricoes.prescricao')),
            ],
        ),
    ]
